### ISSUE TITLE
Add concatenation feature for multiple YAML input files

### ISSUE THREAD

**Issue by victorapm** [hypre-space/hypredrive#11]
Assuming:

1. `base.yml`:
``` yaml
general:
  warmup: no
  num_repetitions: 1

linear_system:
  type: ij
  rhs_filename: IJ.out.b
  matrix_filename: IJ.out.A
  dofmap_filename: dofmap
```
2. `solver.yml`
``` yaml
solver:
  fgmres:
    max_iter: 500
    relative_tol: 1.0e-3
    print_level: 2
```
3. `prec.yml`
```yaml
preconditioner:
  mgr:
    print_level: 1
    level:
      0:
        f_dofs: [0]
        f_relaxation: single
        g_relaxation: none
        restriction_type: injection
        prolongation_type: jacobi
        coarse_level_type: rap
    coarsest_level:
      amg:
        coarsening:
          strong_th: 0.3
```

We would like to do:

```bash
  $ ./hypre_app base.yml prec.yml solver.yml
```

and the YAML inputs would get concatenated internally as:
```yaml
general:
  warmup: no
  num_repetitions: 1

linear_system:
  type: ij
  rhs_filename: IJ.out.b
  matrix_filename: IJ.out.A
  dofmap_filename: dofmap
preconditioner:
  mgr:
    print_level: 1
    level:
      0:
        f_dofs: [0]
        f_relaxation: single
        g_relaxation: none
        restriction_type: injection
        prolongation_type: jacobi
        coarse_level_type: rap
    coarsest_level:
      amg:
        coarsening:
          strong_th: 0.3
solver:
  fgmres:
    max_iter: 500
    relative_tol: 1.0e-3
    print_level: 2
```

We shouldn't have limitations on the number of input files.

Note the order of solver/preconditioner shouldn't matter
