### ISSUE TITLE
Simplify setup of `f_dofs` for MGR

### ISSUE THREAD

**Issue by victorapm** [hypre-space/hypredrive#20]
Instead of passing in numbers, we would like to inform labels (suggested by Matteo), e.g.,

```yaml
preconditioner:
  mgre:
    level:
      0:
        f_dofs: [wells]
      1:
        f_dofs: [water_density]
      2:
        f_dofs: [oil_density]
```

This will require a mapping between dof markers and labels, e.g.:

```yaml
linear_system:
  dof_labels:
    wells: 3
    water_density: 1
    oil_density: 2
    pressure: 0
```

or

```yaml
linear_system:
  dof_labels:
    3: wells
    1: water_density
    2: oil_density
    0: pressure
```
