### ISSUE TITLE
Allow multiple solver configs with a single input file

### ISSUE THREAD

**Issue by victorapm** [hypre-space/hypredrive#25]
We would like to allow something like this:
```yaml
general:
  warmup: no
  num_repetitions: 1

linear_system:
  type: ij
  rhs_filename: IJ.out.b
  matrix_filename: IJ.out.A

solver:
  pcg:
    relative_tol: 1.0e-9
    max_iter: 500
    print_level: 3

preconditioner:
  amg:
    -
      print_level: 1
      coarsening:
        type: HMIS
        strong_th: 0.25
      interpolation:
        prolongation_type: MM-ext+i
      relaxation:
        down_type: 16
        down_sweeps: 1
        up_type: 16
        up_sweeps: 1

    -
      print_level: 1
      coarsening:
        type: PMIS
        strong_th: 0.5
      interpolation:
        prolongation_type: standard
      relaxation:
        down_type: 8
        down_sweeps: 2
        up_type: 8
        up_sweeps: 2

  # Add more configurations as needed
```

Also, something like this:

```yaml
general:
  warmup: no
  num_repetitions: 1

linear_system:
  type: ij
  rhs_filename: IJ.out.b
  matrix_filename: IJ.out.A

solver:
  pcg:
    relative_tol: 1.0e-9
    max_iter: 500
    print_level: 3

preconditioner:
  amg:
    - config_1.yml
    - config_2.yml
```

And same for solver...

`hypre_app` would then run all possible combinations.

This can be the early stage of an autotuner.
