### ISSUE TITLE
Read sequence of linear systems

### ISSUE THREAD

**Issue by victorapm** [hypre-space/hypredrive#3]
We currently support only one linear system (matrix, rhs, dofmap) per YAML input. 

The idea here is to allow users to pass in a sequence of linear systems (different matrices and vectors) to be solved by the given preconditioner/solver strategy defined in the YAML input.

Need to allow for a new `linear_system` structure in the YAML file. Example:
``` yaml
linear_system:
  directory:
    base: hypre-data/ls_
    init_suffix: 00000
    last_suffix: 00349
  matrix_filename: IJ.A.out
  rhs_filename: IJ.b.out
  dofmap_filename: dofmap.out 
```

This would read all:

- matrices with prefix name as `IJ.A.out` defined in the sub-directories starting from `./hypre-data/ls_00000` up to `./hypre-data/ls_00349`.
- Same as above for the rhs vectors
- Same as above for the dofmap vectors
