### ISSUE TITLE
Fix YAML syntax

### ISSUE THREAD

**Issue by victorapm** [hypre-space/hypredrive#7]
We need to fix some issues in the syntax of our YAML strategy, which is not currently compliant with the standard.

Target one should be something like:
```yaml
general:
  warmup: no
  num_repetitions: 1

linear_system:
  type: ij
  rhs_filename: IJ.out.b
  matrix_filename: IJ.out.A
  dofmap_filename: dofmap.out

solver:
  type: fgmres
  print_level: 2
  tolerance: 1.0e-6
  max_iterations: 500
  subspace_dim: 30

preconditioner:
  type: mgr
  print_level: 1
  pmax: 0
  levels:
    0:
      f_dofs: [0]
      f_relaxation:
        type: jacobi
        sweeps: 1
      g_relaxation: none
      restriction_type: injection
      prolongation_type: jacobi
      coarse_level_type: rap # coarse_level? schur_comp? reduction_strategy?
    1:
      f_dofs: [1]
      f_relaxation: none
      g_relaxation:
        type: ilu
        subtype: fill
        fill: 0
        sweeps: 1
      restriction_type: injection
      prolongation_type: jacobi
      coarse_level_type: cpr-like-bdiag

  coarse_solver: # coarsest_solver?
    type: boomeramg
    print_level: 0
    strong_th: 0.3
    pmax: 6
```
